### ISSUE TITLE
作者你好，软件很不错。有个问题：在win10下，排序方式，图片比例的字体显示不全。有个建议，是否可以增加一个开机自启动的功能？谢谢！

### ISSUE THREAD

**Issue by ghost** [leoFitz1024/wallhaven#1]
![image](https://user-images.githubusercontent.com/97387048/148679753-74e99e7a-a04d-4dad-9d96-cfdd76c6bd2a.png)

**Comment by leoFitz1024** [comment]
我在弄v2版本，我嫌这个太丑了哈哈哈，qt还不咋会，v2会加上开机自启

**Comment by ghost** [comment]
谢谢你的回复，期待！😁

**Comment by liwenjie119** [comment]
> 我在弄v2版本，我嫌这个太丑了哈哈哈，qt还不咋会，v2会加上开机自启

期待更新，现在win11打不开软件

**Comment by leoFitz1024** [comment]
更新啦更新啦

**Comment by Wanh2022** [comment]
V2提示 Request failed with status code 500

**Comment by Wanh2022** [comment]
![1645084348(1)](https://user-images.githubusercontent.com/66768440/154430065-2db3ac20-bfc8-4ccc-844f-24800690240f.png)
