### ISSUE TITLE
一直报错  异常请求：request failed with status code 500

### ISSUE THREAD

**Issue by georgez1379** [leoFitz1024/wallhaven#10]
在线图标都加载不出来，首页也是network error
![Snipaste_2022-04-14_10-11-44](https://user-images.githubusercontent.com/63297611/163300249-25f05ec0-9743-49fd-9d38-6e0f2099ca71.png)
![7L 3`%(NU4NT(7DYW0AJ7MG](https://user-images.githubusercontent.com/63297611/163300263-0ef50b2d-d14c-4906-97ae-1cab714f1e8a.png)

**Comment by chensir201314** [comment]
老哥，这种的情况该怎么解决？

**Comment by chensir201314** [comment]
win11完美运行此软件

**Comment by chensir201314** [comment]
win10运行会出现此问题

**Comment by georgez1379** [comment]
Windows10怎么解决呀？我下了1.0版本也是也是一样报错

**Comment by pdy265** [comment]
我是win10 64位也是这个情况。

**Comment by lxsamazing** [comment]
把代理关了

**Comment by iwushaoling** [comment]
你们怎么解决的。。。只能关代理吗

**Comment by lxsamazing** [comment]
> 

代理添加直连规则也行

**Comment by leoFitz1024** [comment]
群里发布了3.0版本
