### ISSUE TITLE
大大！请求添加“下载分辨率”设置功能，使得在线切换or下载时可以设置分辨率。

### ISSUE THREAD

**Issue by Lyshc-cgc** [leoFitz1024/wallhaven#13]
@leoFitz1024 
1.作者大大你好，3.0我已经用起来了，没有了之前无法加载图片的bug。后续更新，可否考虑**增加“分辨率”设置**的功能，使得在线切换壁纸或者下载壁纸时，直接转换为设定好的分辨率。相当于wallheaven中的**[Crop & Scale Download]**功能。 
2.这样的话，不同用户的根据自己屏幕参数进行设置后，下载|切换的壁纸可以很好地适配各自的屏幕。相比于选择“填充模式”，自定义分辨率屏幕适配效果更好。
3.当然，如果**定时切换**也能自定义时间就更好了。

**Comment by leoFitz1024** [comment]
分辨率这个是有这个功能的，在线列表那里修改分辨率过后，可以点击刷新旁边的保存按钮，设置为在线切换的参数

**Comment by leoFitz1024** [comment]
自定义时间后面加上

**Comment by Lyshc-cgc** [comment]
哦哦，整明白了，感谢回复！
