### ISSUE TITLE
本地切换功能优化

### ISSUE THREAD

**Issue by oceangle** [leoFitz1024/wallhaven#25]
本地切换似乎是按照图片下载的时间来切换的，是否可以增加一个随机切换功能，在本地下载目录内随机选择一张来作为壁纸？

**Comment by leoFitz1024** [comment]
后续可以加上

**Comment by leoFitz1024** [comment]
[Release-4.1.0](https://github.com/leoFitz1024/wallhaven/releases) 已支持
