### ISSUE TITLE
wallhaven.cc被墙了，软件加载不了图片

### ISSUE THREAD

**Issue by cuiwenpei** [leoFitz1024/wallhaven#34]
wallhaven.cc被墙了，软件加载不了图片

**Comment by 2353672932** [comment]
有人能分享个VPN的软件吗，免费的，可以适配waiihaven，求求了

**Comment by WIoly** [comment]
软件我开了好像还是用不了，不知道是不是设置错误了

**Comment by hzl7103** [comment]
设置网络代理。。有大佬验证过可行吗？

**Comment by leoFitz1024** [comment]
现在已经解决，只要设置了系统代理软件就默认走系统代理，不需要在设置软件内代理
下载最新版【4.2.0】解决

> 软件我开了好像还是用不了，不知道是不是设置错误了



> 设置网络代理。。有大佬验证过可行吗？
