### ISSUE TITLE
关于网络代理设置

### ISSUE THREAD

**Issue by hzl7103** [leoFitz1024/wallhaven#36]
大佬能否考虑对网络代理设置做进一步说明？
比如目前被墙环境下能否通过代理访问

**Comment by leoFitz1024** [comment]
现在已经解决，只要设置了系统代理软件就默认走系统代理，不需要在设置软件内代理
下载最新版【4.2.0】解决

**Comment by 2353672932** [comment]
我下载了[4.2.0]用了，可是还是没用啊，还是显示网络异常，公众号上也没有详细的攻略，难受
