### ISSUE TITLE
关于软件代理设置的建议

### ISSUE THREAD

**Issue by TMDW** [leoFitz1024/wallhaven#4]
作者您好，软件很棒，但可否在软件中加入代理设置开启cfw后，python默认情况下无法联网

**Comment by sakura-love** [comment]
请问你也遇到了local host无法访问的问题吗，请问是如何解决的

**Comment by TMDW** [comment]
是的，然后我就把系统代理关了……

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sakura-love ***@***.***&gt;
发送时间: 2022年3月15日 16:43
收件人: leoFitz1024/wallhaven ***@***.***&gt;
抄送: TMDW ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [leoFitz1024/wallhaven] 关于软件代理设置的建议 (Issue #4)





 
请问你也遇到了local host无法访问的问题吗，请问是如何解决的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sakura-love** [comment]
...系统代理关了？？？是这样吗
![image](https://user-images.githubusercontent.com/34211533/158541322-0c8464b0-de62-4424-ae52-2f7d2e230d14.png)

**Comment by TMDW** [comment]
是的，关掉代理后就可以用了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sakura-love ***@***.***&gt;
发送时间: 2022年3月16日 15:47
收件人: leoFitz1024/wallhaven ***@***.***&gt;
抄送: TMDW ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [leoFitz1024/wallhaven] 关于软件代理设置的建议 (Issue #4)





 
...系统代理关了？？？是这样吗
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zero617** [comment]
我关闭系统里后依旧无法使用

**Comment by Yamazaki-wu** [comment]
建议作者能在软件设置里加入代理选项，socks或者http都行。
刷新壁纸时经常会提示网络异常或network error

**Comment by leoFitz1024** [comment]
4.0.0以增加设置代理功能
