### ISSUE TITLE
功能建议及感谢

### ISSUE THREAD

**Issue by LcDesign001** [leoFitz1024/wallhaven#47]
这个软件很好的帮助我解决了访问wallhaven的问题，而且还能够快速设置第二个显示器的屏幕壁纸，太酷了，之前找了很多办法都没办法实现win10下双屏不同壁纸的设置，有个小小的建议，本地壁纸那里可以增加文件夹穿透的的功能吗？类似看图软件能够看到文件夹内的其他文件夹，壁纸下了比较多有做分类，但目前只能手动一个个文件夹切换，不能穿透预览或选择设置

**Comment by leoFitz1024** [comment]
这个暂不考虑的，因为软件本地列表功能主要是为了显示下载的图片，不是用来作为查看图片的工具的
