### ISSUE TITLE
【需求】希望搜索框增加回车搜索功能

### ISSUE THREAD

**Issue by cornradio** [leoFitz1024/wallhaven#49]
![image](https://github.com/leoFitz1024/wallhaven/assets/119606491/c90e45d9-46a6-49cb-a35c-70c98fd1e4af)

就这个搜索框，每次打完字之后，按下回车都没有反应，要用鼠标点一下搜索按钮才会执行搜索。

这样用起来非常的麻烦~ 可以更新成能enter搜索么？

**Comment by leoFitz1024** [comment]
可以

**Comment by leoFitz1024** [comment]
v4.4.4-已实现

**Comment by cornradio** [comment]
v4.4.4 似乎会让电脑变得很卡
