### ISSUE TITLE
希望加入wallhaven的订阅功能

### ISSUE THREAD

**Issue by jsdfhasuh** [leoFitz1024/wallhaven#58]

**Comment by leoFitz1024** [comment]
需求描述不清晰

**Comment by jsdfhasuh** [comment]
> 需求描述不清晰
类似这样，获取某作者的上传
![image](https://github.com/leoFitz1024/wallhaven/assets/49879362/eb74cbf1-b96f-4a45-869d-5b76557d78ef)
