### ISSUE TITLE
BUG report

### ISSUE THREAD

**Issue by sakura-love** [leoFitz1024/wallhaven#6]
这是bug还是设置问题呢？其他应用上，除了虚拟机配置我至今还没有遇到过类似的问题
![image](https://user-images.githubusercontent.com/34211533/158339017-fc35e62e-9086-400f-8270-2d70641f4700.png)

**Comment by qljlyrh** [comment]
我的电脑也遇到了 奇怪的是我公司的电脑没问题 都是win10的系统

**Comment by leoFitz1024** [comment]
2.0是存在这个问题，群里发布了3.0版本，可以下在，后面我有空了我也会在这里发布一下
